// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCci3H_04XqGuQr5flEBRA_YwNMaqjvP0',
    appId: '1:950644538788:web:96df3afdc33e1209729531',
    messagingSenderId: '950644538788',
    projectId: 'truthsoko',
    authDomain: 'truthsoko.firebaseapp.com',
    storageBucket: 'truthsoko.appspot.com',
    measurementId: 'G-GV2E4G65GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvSBxEGOkVGhhVvd-KC-bizRknzgRNfmI',
    appId: '1:950644538788:android:545ffdc83d357798729531',
    messagingSenderId: '950644538788',
    projectId: 'truthsoko',
    storageBucket: 'truthsoko.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS_ZMqZPR1-qBnKEZXlJ9kk8h30vHCjZE',
    appId: '1:950644538788:ios:3b7f3cc8d8ba61d3729531',
    messagingSenderId: '950644538788',
    projectId: 'truthsoko',
    storageBucket: 'truthsoko.appspot.com',
    androidClientId: '950644538788-mgvo8cdlp7m8q1usqk3f4ft8kb6glcug.apps.googleusercontent.com',
    iosClientId: '950644538788-26dlkob1don5gjk9b8thja6mh8u90t2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.truthsoko',
  );
}
